import AppKit
import Observation

nonisolated enum ClipboardFilter {
    static let concealedType = "org.nspasteboard.ConcealedType"
    static let transientType = "org.nspasteboard.TransientType"
    static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"
    static let blockedTypes: Set<String> = [concealedType, transientType, autoGeneratedType]

    /// Added to everything Clippy itself writes so the monitor doesn't re-capture it.
    static let internalMarkerType = "at.softmaze.clippy.internal"

    enum Decision: Equatable, Sendable {
        case capture
        case blockedType
        case ignoredApp
        case ownWrite
        case empty
    }

    static func decide(types: [String], sourceBundleID: String?, ignoredBundleIDs: Set<String>) -> Decision {
        if types.isEmpty { return .empty }
        if types.contains(internalMarkerType) { return .ownWrite }
        if types.contains(where: blockedTypes.contains) { return .blockedType }
        if let sourceBundleID, ignoredBundleIDs.contains(sourceBundleID) { return .ignoredApp }
        return .capture
    }
}

enum PasteboardReader {
    static let maxTextLength = 5_000_000          // UTF-16 units
    static let maxRichDataBytes = 10 * 1024 * 1024
    static let maxImageBytes = 64 * 1024 * 1024

    static func read(_ pb: NSPasteboard, source: AppRef?) -> RawCapture? {
        let types = Set(pb.types ?? [])

        if types.contains(.fileURL),
           let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return RawCapture(kind: .file, fileURLs: urls, source: source)
        }

        if let string = pb.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard string.utf16.count <= maxTextLength else {
                Log.capture.info("Skipping oversized text (\(string.utf16.count) units)")
                return nil
            }
            let rtf = types.contains(.rtf) ? pb.data(forType: .rtf).flatMap { $0.count <= maxRichDataBytes ? $0 : nil } : nil
            let html = types.contains(.html) ? pb.data(forType: .html).flatMap { $0.count <= maxRichDataBytes ? $0 : nil } : nil
            return RawCapture(
                kind: (rtf != nil || html != nil) ? .richText : .text,
                text: string,
                rtfData: rtf,
                htmlData: html,
                source: source
            )
        }

        if types.contains(.png) || types.contains(.tiff),
           let data = pb.data(forType: .png) ?? pb.data(forType: .tiff),
           data.count <= maxImageBytes {
            return RawCapture(kind: .image, imageData: data, source: source)
        }

        return nil
    }
}

/// Polls `NSPasteboard.changeCount`. macOS has no pasteboard-change notification, and reading an
/// integer twice a second is effectively free; actual reads only happen when the count moves.
@Observable
final class ClipboardMonitor {
    @ObservationIgnored private let pasteboard: NSPasteboard
    @ObservationIgnored private let store: ClipStore
    @ObservationIgnored private let prefs: Preferences
    @ObservationIgnored private let tracker: FrontmostAppTracker
    @ObservationIgnored private let blobs: BlobStore
    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var lastChangeCount = 0

    private(set) var captureCount = 0
    /// Lets the app veto a processed capture (e.g. text that equals a saved secret).
    @ObservationIgnored var shouldDiscard: ((ProcessedCapture) -> Bool)?

    init(store: ClipStore, prefs: Preferences, tracker: FrontmostAppTracker, blobs: BlobStore, pasteboard: NSPasteboard = .general) {
        self.store = store
        self.prefs = prefs
        self.tracker = tracker
        self.blobs = blobs
        self.pasteboard = pasteboard
    }

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.tick() }
        }
        timer.tolerance = 0.15
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard !prefs.isPaused else { return }
        autoreleasepool { captureCurrent() }
    }

    private func captureCurrent() {
        let types = pasteboard.types?.map(\.rawValue) ?? []
        let source = tracker.currentSource
        let decision = ClipboardFilter.decide(
            types: types,
            sourceBundleID: source?.bundleID,
            ignoredBundleIDs: prefs.ignoredBundleIDs
        )
        guard decision == .capture else {
            Log.capture.debug("Skipped pasteboard change: \(String(describing: decision), privacy: .public)")
            return
        }
        guard let raw = PasteboardReader.read(pasteboard, source: source) else { return }

        let blobs = self.blobs
        Task { [weak self] in
            guard let processed = await CaptureProcessor.process(raw, blobs: blobs) else { return }
            guard let self else { return }
            if self.shouldDiscard?(processed) == true {
                blobs.delete(processed.imageFile)
                blobs.delete(processed.thumbnailFile)
                return
            }
            self.store.ingest(processed)
            self.store.enforceRetention(maxItems: self.prefs.maxItems, maxAge: self.prefs.maxAge)
            self.captureCount += 1
        }
    }
}
